### ISSUE TITLE
Example project failing at build

### ISSUE THREAD

**Issue by AJFeather** [linkedin/pygradle#130]
This appears to be a similar issue to https://github.com/linkedin/pygradle/issues/42, but I checked the setup.py file and the bottom section was commented out as suggested in that post.

```
Install example-project ............................................. [STARTING]
Obtaining file:///pygradle-master/examples/example-project
No files/directories in /pygradle-master/examples/example-project (from PKG-INFO)
:installProject FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installProject'.
> Failed to install example-project. Please see above output for reason, or re-run your build using ``ligradle -i build`` for additional logging.
```

**Comment by sixninetynine** [comment]
Hi @AJFeather do you mean that it was _not_ commented out? After running `./gradlew generateSetupPy` you get a `setup.py` file that has the call to `setup` commented out. In order to build your python project these lines should _not_ be commented out. 

> The setup.py in this example was created using the above task, by default the "setup" section at the bottom is commented out, so please look it over before continuing. **For this example we want to uncomment the whole section at the bottom of the setup.py.**
> 
> Note: The generateSetupPy task should only be used to bootstrap a project and should be checked in to a project.

Running `./gradlew build` worked fine for me. Are you running `./gradlew build` inside the `example-project` directory (it won't work from the root of repo)?

**Comment by AJFeather** [comment]
Well, this is rather embarrassing. I guess I misread that. It's working now.
