### ISSUE TITLE
PipInstallTask should always install SNAPSHOT versions

### ISSUE THREAD

**Issue by schakrava** [linkedin/pygradle#135]
Since we use gradle's inputs/outputs to determine if some package must be pip installed(or upgraded), we should use --upgrade flag to turn off pip's check which is only based on the version

This is helpful on incremental builds where we are updating snapshots/same-versions of dependencies. In such case, gradle runs the pip install task as expected, but pip thinks the dependency is already satisfied:

`Requirement already satisfied (use --upgrade to upgrade):`

**Comment by zvezdan** [comment]
I believe we should not force `--upgrade` for every package, but we can do it for SNAPSHOT versions only. That makes sense for the snapshot usage pattern.

It's quite unfortunate that the snapshot use as done with Gradle is violating a long-time accepted rule that different code should have a different version number. Thus, traditionally, we'd have `a1`, `a2`, etc. for each new change in the `alpha` package, rather then a single `SNAPSHOT` version for all of them. When experimenting, Python developers usually use `--editable` package until the code is stable enough to go out as an `alpha1` or `a1`. Gradle did not provide for such use case, because Java does not have a concept of *editable* packages.

Since we're handling this in a Gradle plugin though, we can provide a workaround for that version numbering anomaly with snapshots and allow `--upgrade` for these packages **only**. The number of snapshots used is usually small enough that the fact they'll get re-installed on *every* build is not going to be a problem.

Until we do, you can use a simple workaround. Activate the Python virtualenv in your project, then `pip uninstall snapshot-package-name`, deactivate and run build. That will re-install the snapshot with the new changes. Other, and perhaps better approach is to use `pip install --editable package-name` and use a snapshot only when done experimenting with the code. Don't forget to uninstall the editable package first. This second approach does not work with deployables/executables because `pexBuild` task will fail due to the editable package being used.

**Comment by schakrava** [comment]
Thanks for your comments @zvezdan. I have updated the title of the issue. I think what we need is the `--ignore-installed` option for package names ending in `-SNAPSHOT`. PR on the way
