### ISSUE TITLE
Setuptools 32.1.+

### ISSUE THREAD

**Issue by scphantm** [linkedin/pygradle#152]
Well, i don't see anyone else asking so I'm going to ask.  Its obvious that you upgraded setuptools to 32.1.1 because in 32.1.2 they started distributing it as a zip file and pygradle gives a "Can't untar file" error.  

Is this a pygradle issue or a python issue?  Any leads on how to fix it?

**Comment by zvezdan** [comment]
PyGradle does **not** use setuptools-32.x.

PyGradle **before** 0.6.x used setuptools-19.1.1.
PyGradle-0.6.x pins setuptools at 33.1.1:

* https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/PythonExtension.groovy#L75
* https://github.com/linkedin/pygradle/blob/master/pivy-importer/build.gradle#L67

Also, PyGradle does not download other versions from pypi during build of python projects.

* https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/InstallVirtualEnvironmentTask.groovy#L95

Here's the output I get on a fresh build of PyGradle HEAD that succeeds without issues:
```
13:01:06.852 INFO  c.l.p.i.deps.DependencyDownloader - Pulling in setuptools:33.1.1
```

Every Python project we build with PyGradle does the same (setuptools is the first thing that gets installed always):
```
Install setuptools-33.1.1 ........................................... [STARTING]
```

You didn't mention what version of PyGradle did you get this with?
Try using the latest.

If you got this error on a checkout of PyGradle that is not fresh and was built before with older version, try cleaning up first using `./gradlew clean` and then building.

I'm inclined to close this issue because the version of setuptools you mention here is definitely not used with pygradle.

**Comment by scphantm** [comment]
im running a fork because i had to completely rebuild pivy to work on our network.  since we don't have python 2 in our enterprise anymore i upgraded the setuptools to 36 and got the error.  Whats going on is 33.1.1 is a tarball, but 33.1.2 on is a zip.  the pygradle tools pull down the zip properly and its in the cache folders correctly, but when it tries to pip, it trys to untar a zip file.  Im pretty sure thats why you guys stopped with 33.1.1, just wondering if you had a sense of how to fix it.

use your python extension to force 33.1.2+ and you should see the error.

**Comment by scphantm** [comment]
wait, i see what you are saying, you are using the zip version too

WTF, i hate our network.  we have pypi actively blocked on our firewall so whenever distutils tries to resolve the setup_requires, test_requires, etc, and dist utils tries to hit pypi for the meta files, it blows up.  and i can't get distustils to recognize the pypirc file on windows.  so i completely rebuilt pivy to parse the setup.py files and extract all dependencies and put them in the ivy file.  been working very well so far, but this brought me to a halt when i upgraded the thing to setuputils 36, hoping that version would pick up the pypirc file correctly.

its been a week of hell.
