### ISSUE TITLE
Can't resolve plugin version 0.6.10

### ISSUE THREAD

**Issue by mangan77** [linkedin/pygradle#162]
Trying to apply the latest plugin version does not work. We tried both ways to apply the plugin, but no one work. The plugin simply can't be found:

`* What went wrong:
A problem occurred configuring root project 'XXXX'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.linkedin.pygradle:pygradle-plugin:0.6.10.
     Searched in the following locations:
         https://repo1.maven.org/maven2/gradle/plugin/com/linkedin/pygradle/pygradle-plugin/0.6.10/pygradle-plugin-0.6.10.pom
         https://repo1.maven.org/maven2/gradle/plugin/com/linkedin/pygradle/pygradle-plugin/0.6.10/pygradle-plugin-0.6.10.jar
         https://plugins.gradle.org/m2/gradle/plugin/com/linkedin/pygradle/pygradle-plugin/0.6.10/pygradle-plugin-0.6.10.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/linkedin/pygradle/pygradle-plugin/0.6.10/pygradle-plugin-0.6.10.jar
     Required by:
         project :`

Import statement:

`plugins {
  id "com.linkedin.python" version "0.6.10"
}
`

**Comment by dobe** [comment]
same here.

also - where can i find out which version is the current stable versions for the pygradle plugins?

**Comment by mangan77** [comment]
@dobe I would presume that the one listed in the plugins repo is the latest stable: https://plugins.gradle.org/plugin/com.linkedin.python

**Comment by zsimic** [comment]
+1 I'm getting the exact same issue with the latest pygradle versions

**Comment by zvezdan** [comment]
Sorry, we were not aware of this because we're using the plugins internally at LinkedIn without any issues. Moreover, the new versions of plugins are uploaded to the internal repo using an automated service and it worked fine.

We published all recent versions the same way we always used. We'll investigate if something had changed recently and needs to be done differently now.

In the meantime, you can use the last version that is available for download. We had 0.6.3 reported and above 0.6.5.

Regarding the last stable version, that's the version uploaded to plugins.gradle.org -- so 0.6.10
If you have dependencies on pre-release packages, we recommend staying on 0.6.8, though.
There are two bugs in PEX itself revealed with pygradle-0.6.9 that we're filing the issue/fix for in PEX.
We mitigated for one of them in 0.6.10, but the second one must be fixed in PEX.
If you don't have pre-release dependencies (alpha, beta, rc1, ...), 0.6.10 is a good choice.
Notice that pip does not allow pre-release dependencies by default, so most of the users will be OK with it.

**Comment by ethankhall** [comment]
We're working with Gradle Inc to figure out why this is happening. Will let you know when we've resolved it. Sorry for the inconvenience.
