### ISSUE TITLE
PIP>9.0.3 breaks usage of local repository for python plugins

### ISSUE THREAD

**Issue by trillejs** [linkedin/pygradle#249]
As seen in the following logs : [log.txt](https://github.com/linkedin/pygradle/files/2442684/log.txt)
Changing the default pip version for the venv to 9.0.3 solves the problem.
I use ivypot and the pivy-importer to create a project I can build offline.
However the use of PIP10 and above breaks this capability to install some packages offline, the build works fine when connected to the internet.
Note that simply passing the --offline argument to gradle does not reproduce the problem since packages will still be installed from online repo.

**Comment by zvezdan** [comment]
@trillejs Yes, pip now supports [PEP 518](https://www.python.org/dev/peps/pep-0518). To control its behavior in an environment that does not allow outside access, one needs to specify certain options and ensure certain requirements. See the paragraph starting with "In certain cases, ..." in pip documentation: https://pip.pypa.io/en/stable/reference/pip/#pep-518-support

To apply this setting with pygradle build, you can use an approach similar to the test fixes shown in the recent PR #248 changed files. To use it with multiple projects without changing their build.gradle files, similar code can be put in a plugin that uses pygradle and is applied by these projects. That's the approach we use internally.

I assume you are aware that the main limitation for upgrades of setuptools, wheel, pip, and virtualenv is pex. Until recently it only supported setuptools < 34.0.0 and wheel < 0.30.0. Only pex-1.4.6 added support for recent releases of setuptools and wheel, but it had a serious bug. It was fixed in pex-1.4.7 and that's the version we just upgraded to in the PR above.

I just released this upgrade on plugins.gradle.org as pygradle-0.8.10. We always recommend using matching versions of setuptools, wheel, pip, virtualenv, and pex. That's why we pin them in pygradle. The release 0.8.10 has all the latest versions of these Python packaging tools (except wheel-0.32.0 that was just released and pex limits it to wheel < 0.32.0).

Let us know if this info helped.

**Comment by trillejs** [comment]
Thanks a bunch, passing the argument to pip works.

> We always recommend using matching versions of setuptools, wheel, pip, virtualenv, and pex. That's why we pin them in pygradle.

I understand, but it could be more explicit in the documentation that these are forced in some file in the plugin because it was a pain to override. 
It should be possible to change the versions in the same way that the [python{} parameters are passed](https://github.com/linkedin/pygradle/blob/master/docs/plugins/python.md).

**Comment by trillejs** [comment]
I tried using forceVersion but it was not taken into account. Maybe an error on my end, I'll check again.
Yeah documentation is always the neglected child of programming. 
Maybe forceVersion shouldn't be used if there is also a dependecies{} bloc, it is confusing.
I use a dependency.gradle file  to handle what the pivy-importer needs to download and using dependencies instead of forceVersion would also remove the need to duplicate this info.

**Comment by zvezdan** [comment]
@trillejs I'm glad it helped.

Just to clarify in case I misunderstood your use case.

We do use `dependencies { ... }` closure to specify our product's *direct* dependencies.
Most of the time they will be the *runtime* dependencies in the `python` configuration (in Gradle terms) or the *test* dependencies in the `test` configuration. Such as:
```
dependencies {
    python 'pypi:requests:2.19.1'
    test 'pypi:mock:2.0.0'
}
```
There are two more configurations: `build` and `setupRequires`.

We provide *automatically* the ones that are needed, so *most of the time* you don't need to declare them in your direct dependencies. The `setupRequires` configuration is automatically populated with _setuptools_, _wheel_, _pip_, and _setuptools-git_. The `build` configuration is filled with _flake8_ and _Sphinx_. Finally, the `test` configuration has _pytest_, _pytest-cov_, and _pytest-xdist_. Thus, you don't need to declare any of these in your dependencies.

However, since their versions are pinned to the matching versions that we extensively test internally, if you need to change them, you need to use `forceVersion()` in the `python { ...}` extension closure where all custom settings are applied. There's no need to duplicate them in the `dependencies { ... }` section. They are already properly added into your dependencies in the proper configuration for their *typical* usage.

If your product is a library, that's pretty much all you need to know. If you product is a deployable, and it produces a PEX file, then it's important to know that *only* the dependencies listed in `python` configuration will be packed into PEX. To avoid confusion because of the same name, these are in `dependencies { python 'pypi:...:...' // ... etc }` closure; that's unrelated to the extension `python { details.pythonVersion = '3.6' // ... etc. }` closure. The `build`, `test`, and `setupRequires` will be dropped since you don't need them for functionality of your product in runtime.

So, here is a case where you may need to include the dependencies we prepared in pygradle. For example, your product needs _setuptools_ or _Sphinx_ in runtime. You would, then, declare them in the `dependencies { ... }` closure as `python 'pypi:...:...` configuration dependencies. That would ensure they are packed into your product's PEX container. If you wanted to change their version too, you would still use `forceVersion()` in the `python { ... }` closure to *override* the `forceVersion()` call for these dependencies in pygradle code. That's the *only* case where it *appears* that there's some duplication. It isn't though, since one entry is to change the version, regardless of the configuration, while the other is to change the configuration of the dependency and ensure it's available at runtime.

Notice that this happens automatically for the transitive dependencies. For example, _Sphinx_ depends on _Jinja2_. So, _Jinja2_ is automatically in `build` dependencies. Lots of web applications need _Jinja2_ as their direct *runtime* dependency (or transitively from some other direct *runtime* dependency). So, _Jinja2_ ends up being in the set of _runtime_ dependencies too, in `python` configuration. In that case, it will be packed into the PEX as runtime dependency to ensure your application has everything it needs to run.

Again, I hope this helps more than confuses the things.

Let me know if we can close this issue now?
We do plan to implement better handling and configuration of this new pip setting in pygradle for pip-10 and later. Still, we do have a setting available right now as shown in my first reply, so perhaps we could consider the issue resolved?

**Comment by trillejs** [comment]
Thank you for the detailed response. As far as I am concerned you can close this issue. 
I understand the need to differentiate the use cases and bundling as forced packages the essentials. 
However it would really be better to unify the different dependencies of a project and make all packages explicit if needs be.

And yes, there are several steps involving different packages, depending on the use cases. In my case I need control on all steps of the building process since I bundle all dependencies for all steps of the project as local ; the integration of the pivy importer is not really done yet. 

It might be interesting to have examples of completely offline builds project using the pivy importer. I can help on that end. Nonetheless, this is a different matter altogether and yes this issue should be closed. Thank you again for your thorough explanations.
