### ISSUE TITLE
Python36 enum34 issue

### ISSUE THREAD

**Issue by jmeekhof** [linkedin/pygradle#268]
I'm attempting to build a project using the Python36 interpreter, and there's a package that calling for enum34, and I can't figure out how to prevent it from being installed. Any suggestion regarding which of the built in packages are calling for this or how to prevent it from being installed?

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jmeekho/projects/vof/mail-extract/build/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/Users/jmeekho/projects/vof/mail-extract/build/venv/lib/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/Users/jmeekho/projects/vof/mail-extract/build/venv/lib/python3.6/imp.py", line 27, in <module>
        import tokenize
      File "/Users/jmeekho/projects/vof/mail-extract/build/venv/lib/python3.6/tokenize.py", line 33, in <module>
        import re
      File "/Users/jmeekho/projects/vof/mail-extract/build/venv/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
```

```gradle
plugins {
    id 'com.linkedin.python-cli' version '0.9.9'
}

python {
    testDir = file("tests")
    details.pythonVersion = '3.6'
    details.systemPythonInterpreter = '/usr/local/bin/python3.6'
}
project.tasks.findByName('installPythonRequirements').sorted = false

dependencies {
    python 'pypi:DateTime:4.3'
    python('pypi:exchangelib:1.12.1') {
        exclude module: 'enum34'
    }
}


repositories {
 ivy {
    name 'pypi-local'   //optional, but nice
    url './repo'
    layout "pattern", {
      ivy "[organisation]/[module]/[revision]/[module]-[revision].ivy"
      artifact "[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"
      m2compatible = true
    }
  }
  pyGradlePyPi()
}

python.cli.generateCompletions = true
```

**Comment by zvezdan** [comment]
You can try finding if Gradle considers it a dependency, or one of your Python packages asks for it.

To look for it using Gradle try:
```
/path/to/gradlew dependencyInsight --configuration python --dependency enum34
```
Replace `python` with `build`, `test`, or `setupRequires` to check other configurations besides the runtime `python` configuration.

You can also check the Python package metadata:
```
cd build/venv/lib/python2.7/site-packages/
find . -type f -exec grep -H "Requires-Dist: enum34" {} \;
```
The output should show the **conditional** dependency only. For example:
```
./Sphinx-1.8.1.dist-info/METADATA:Requires-Dist: enum34; (python_version<"3") and extra == 'test'
./flake8-3.6.0.dist-info/METADATA:Requires-Dist: enum34; python_version<'3.4'
```
If you get an unconditional dependency on `enum34`, then that Python package needs to fix its metadata.

If you get the dependency through Gradle, and the build is failing because Gradle thinks it *needs* it as a dependency there may be some workarounds, but let's first see what is the package in question.

For what it's worth, we have internally at LinkedIn several plugins that deal with builds of products with multiple versions of Python. They provide features that allow:

* declaring the versions of Python that library supports
* declaring environment markers -- conditions under which the package is a dependency
* automatic exclusion of known backports from Python 3 to 2, such as enum34
* updates to DistGradle class used in setup.py to support these new features

We need to port these to open-source pygradle. Obviously, this is not going to happen overnight. They would certainly solve your issue, but until we port them we'll try to work around this with you, once we know what is the package causing this issue.

**Comment by jmeekhof** [comment]
Thanks for the quick reply. What I'm seeing is that Flake is at fault here:
```
pypi:enum34:1.1.6
   variant "default" [
      org.gradle.status = integration (not requested)
   ]

pypi:enum34:1.1.6
\--- pypi:flake8:3.6.0
     \--- build
```

**Comment by zvezdan** [comment]
Workarounds:

* Try putting in the `python { ... }` closure: `forceVersion("pypi", "flake8", "3.2.1")` if you can use lower version of flake8. It seems that versions below 3.3.0 did not have that dependency.
* Alternatively, use older version of pygradle that did not update to flake8-3.6.0.

Notice that there's nothing wrong here with the flake8 itself. It declares the dependency **conditionally** in its Python package metadata. It's the Ivy format used by Gradle that has no notion of conditional dependencies that's at fault. So, the full solution would be porting our plugins mentioned above.

I hope this helps you.

**Comment by jmeekhof** [comment]
Using an earlier `forcedVersion` did the trick. Thanks.

```gradle
python {
    testDir = file("tests")
    details.pythonVersion = '3.6'
    details.systemPythonInterpreter = '/usr/local/bin/python3.6'
    forceVersion('pypi', 'flake8', '3.2.1')

}
```
