### ISSUE TITLE
flake8 plugins - how to enable them?

### ISSUE THREAD

**Issue by Nickolaim** [linkedin/pygradle#284]
How to install flake8 plugins so they are executed during `gradlew flake8`? 

`flake8` that is used for this command is in `build/infra-ven` and I could not find a way to have plugins land into this virtual environment. 

Please suggest.

**Comment by zvezdan** [comment]
In general flake8 and Sphinx plugins should be declared as a `build` configuration dependency  (as opposed to `python` runtime dependency or `test` dependency).
Now, after the move of flake8 task you may need to declare `flake8` configuration dependency, or perhaps both `build` and `flake8`.

We've noticed this regression and since the reason it was made does not apply any more, we're planning on reverting that change once we finish some more urgent work and features we're busy with now. When we restore the old behavior, you should be able to use just `build` configuration dependency as you did before.

I hope the suggestion above helps in the meantime.

**Comment by Nickolaim** [comment]
Thank you, it helped!

Feel free to keep this issue as a reminder to revert the change.  Or just close it.

Thanks again.
