### ISSUE TITLE
Exclude dependency from Python3 build?

### ISSUE THREAD

**Issue by blankdots** [linkedin/pygradle#96]
I am trying to build a project with python 3.4 and during build i get an error at one of the dependencies and it looks like:
```
Install functools32-3.2.3-2 ......................................... [STARTING]
Starting process 'command '/home/user/project/build/venv/bin/python''. Working directory: /home/user/project Command: /home/user/project/build/venv/bin/python /home/user/project/build/venv/bin/pip install --disable-pip-version-check --no-deps /home/user/.gradle/caches/modules-2/files-2.1/pypi/functools32/3.2.3-2/a520082a56af52c7af8d2d1390856bf1a0d755df/functools32-3.2.3-2.tar.gz
Successfully started process 'command '/home/user/project/build/venv/bin/python''
Processing /home/user/.gradle/caches/modules-2/files-2.1/pypi/functools32/3.2.3-2/a520082a56af52c7af8d2d1390856bf1a0d755df/functools32-3.2.3-2.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/user/1261914/pip-76419vxe-build
:project:installPythonRequirements FAILED
:project:installPythonRequirements (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.565 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project:installPythonRequirements'.
> Failed to install functools32-3.2.3-2. Please see above output for reason, or re-run your build using ``gradle -i build`` for additional logging.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

I should also mention that I am able to build and test the application in Python 2.7.6 using Gradle without any problem and that when creating a virtual environment for Python 3 specific for this project I do not run into any issues installing the dependencies (... even tried matching the version of my pip with `forceVersion`).

The `build.gradle` looks like:
```
plugins {
  id "com.linkedin.python-cli" version "0.3.36"
}

version=0.1

python {
  testDir = file('tests')
  details.prependExecutableDirectory(new File('/usr/bin/python3.4'))
  details.pythonVersion = '3.4'
}
// I did try with and without this option, maybe the order is wrong, trying to identify dependency which causes it.
project.tasks.findByName('installPythonRequirements').sorted = false

dependencies {
    python 'pypi:pathlib:1.0.1'
    python 'pypi:connexion:1.0.129'
    python 'pypi:lxml:3.6.4'
    python 'pypi:beautifulsoup4:4.5.1'
    python 'pypi:rdflib:4.2.1'
    python 'pypi:rdflib-jsonld:0.4.0'
    python 'pypi:PyMySQL:0.7.9'
    python 'pypi:gunicorn:19.6.0'
    python 'pypi:pytest-html:1.12.0'
    test 'pypi:nose:1.3.7'
}

repositories {
    // using a local repository
    ivy{
      name 'pypi-local'
  		url "/home/user/pivy"
  		layout 'pattern' , {
  			artifact '[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]'
  			ivy '[organisation]/[module]/[revision]/[module]-[revision].ivy'
  		}
  	}
}

task wrapper(type: Wrapper) {
   gradleVersion = '3.2.1'
}

task addConfigs(type: Copy) {
    from '.'
    into 'build/deployable'
    include 'database.conf'
}

packageDeployable.dependsOn addConfigs
```
Maybe excluding this from the build might help ... however not sure how to do that?

**Comment by blankdots** [comment]
looking at the dependencies it seems to be caused by jsonschema:
```
+--- pypi:connexion:1.0.129
|    +--- pypi:jsonschema:2.5.1
|    |    +--- pypi:argparse:1.4.0
|    |    +--- pypi:repoze.lru:0.6
|    |    \--- pypi:functools32:3.2.3-2
```
Relate issue: https://github.com/Julian/jsonschema/issues/228 which apparently it should work with Python3, however the problem still appears.

**Comment by zvezdan** [comment]
This happens because the Ivy files do not have the information about the conditional dependencies.
The Python package metadata (when you install in virtualenv) contain the info about `functools32` that limits it to be used with Python 2.7 only (environment markers).

We have solved this internally at LinkedIn last summer. We are able to build libraries that: (a) declare support for multiple versions of Python and get built/tested with each such version, and (b) declare the conditional dependencies so that the environment markers are correctly recorded in the Python package metadata.

Unfortunately, we still did not have time to port these two extensions or the changes to the DistGradle class (used in our setup.py) that are needed to support these features in the open-source pygradle. We are going to work on that as other priorities allow.

In the meantime, you could use Gradle's features and Groovy's `if` statement to exclude the dependencies based on the version of Python interpreter used for the build. That does not scale well for hundreds of products, but can allow you to build a handful of them with Python 3.
Alternatively (and this scales better), you could use your own package repo, where you could store the packages processed with Python 2 separately from those processed with Python 3. That way, the transitive dependencies will not creep in from Python 2 into Python 3 builds.

Notice that pyvi is only a simple example to get users quickly up-and-running with pygradle. Internally, we use a much more sophisticated Python uploader that can use Python 2 or 3 as needed and a professional artifactory repo with python package index. We use a single repo thanks to the above mentioned extensions that allow us to process conditional dependencies correctly.

**Comment by blankdots** [comment]
@zvezdan thank you for the answer. 
I was thinking more and more of seting up my own artifact repository as I have issues with several dependencies, some which are as wheels and I know there is an open issue about that https://github.com/linkedin/pygradle/issues/46 
Meanwhile I was able to built it using the following Gradle construct:
```
dependencies {
    python ('pypi:connexion:1.0.129') {
        exclude module: 'functools32'
    }
}
```
There are still some issues which I was not able (a.k.a. did not have time had time to look into) to solve so I cannot say it  builds properly, but at least it does not get stuck anymore.

**Comment by blankdots** [comment]
Closing this as I think it addressed the main question.
